INSERT INTO Vehicle ('ID', 'Registration_ID', 'Manufacturer', 'Model', 'Color', 'Current_Odometer', 'Passenger_capacity', 'Repair_Action_type') VALUES (1, 11, 'Ford', 'Mondeo', 'Black', 123456, 3, 'M');
INSERT INTO Repair ('Action_type', 'Odometer', 'Final_cost', 'Action_desc', 'Date', 'Vehicle_ID') VALUES ('M', 123456, 230, 'Oil_level', 2022-10-22 ,1);
INSERT INTO Countries ('Name', 'Languages_ID') VALUES ('France' ,'1');
INSERT INTO Games_Officials ('ID', 'Countries_Name', 'Based_city_ID', 'Name', 'Role', 'Languages_ID') VALUES ('1', 'France', 'Paris', 'Olivier Dusoleil', 'Referee', '1');
INSERT INTO Drivers_Informations ('ID', 'Name', 'License_number', 'Clerence_level', 'SLTVT_Level', 'FATL_Level', 'Languages_ID') VALUES ('1' ,'Mark', '84156', '1', '0', '0', '1');
INSERT INTO FATL ('Level', 'Qualification_date', 'Drivers_informations_ID') VALUES ('0' ,'', '84156');
INSERT INTO SLTVT ('Level', 'Qualification_date', 'Certifying_autho', 'Drivers_informations_ID') VALUES ('0' ,'', '', '84156');
INSERT INTO Booking ('ID', 'Trip_start', 'Trip_end', 'Odometer_start', 'Odometer_end', 'Games_Officials_ID', 'Drivers_informations_ID', 'Vehicle_ID', 'Trip_ID') VALUES ('1' ,'2022-10-22 14:12:01', '2022-10-22 14:44:50', '123456', '123467', '1', '1', '1', '1');
INSERT INTO Trip ('ID', 'Pick_Up_ID', 'Drop_Off_ID') VALUES ('1' ,'1', '1');
INSERT INTO Languages ('ID') VALUES ('1');
INSERT INTO Pick_UP ('ID', 'Adress', 'Location_Type') VALUES ('1' ,'232 Inju daero', 'house');
INSERT INTO Drop_Off ('ID', 'Adress', 'Location_Type') VALUES ('2' ,'34 Inha roe', 'complex');